apiVersion: v1
kind: ResourceQuota
metadata:
  name: dev-quota
  namespace: resourcelab
spec:
  hard:
    requests.cpu: "500m"
    requests.memory: "500Mi"
    limits.cpu: "1"
    limits.memory: "1Gi"
    pods: "3"
