events {}

http {
    server {
        listen 80;

        location / {
            return 200 '<h1>Welcome to SRE Labs</h1><p><a href="/api/count">Hit Counter</a></p>';
            add_header Content-Type text/html;
        }

        location /api/ {
            proxy_pass http://api:5000/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /health {
            return 200 'nginx healthy';
            add_header Content-Type text/plain;
        }
    }
}
