apiVersion: v1
kind: Service
metadata:
  name: day42-app
  namespace: day42
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  selector:
    app: day42-app
  ports:
  - port: 80
    targetPort: 80
