apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: day42-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/gdubey12/sre-labs.git
    targetRevision: HEAD
    path: day42
  destination:
    server: https://kubernetes.default.svc
    namespace: day42
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
